version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/usr/src/app
    command: ["node", "server.js"]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"