apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddos-mitigation-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ddos-mitigation
  template:
    metadata:
      labels:
        app: ddos-mitigation
    spec:
      containers:
      - name: ddos-server
        image: ddos-mitigation:latest
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: ddos-service
spec:
  selector:
    app: ddos-mitigation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer